### ISSUE TITLE
Close ths repo

### ISSUE THREAD

**Issue by stemount** [MrWittman612/NewApp100#3]
@MrWittman612 suggestion to just close or private this repo as it is majority broken.

**Comment by MrWittman612** [comment]
I have updated the repo you should be able to run the script 'npm run start:dev' in the root folder navigate to localhost 3000 and register a user login go to a dashboard page and logout the localhost:3000/ is a landing page. Have a good day

**Comment by stemount** [comment]
oh, sorry, my bad I didn't realise you had finished it off, good one!

I thought we left it as got all distracted in a Docker problem! Closing!
